# Generated by Django 2.2.3 on 2019-08-05 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, help_text='Count of tires available', verbose_name='Count')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balance',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Contractor')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone number')),
                ('tires', models.ManyToManyField(through='stock.Balance', to='tires.Tire')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Contractor', verbose_name='Contractor'),
        ),
        migrations.AddField(
            model_name='balance',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.Tire', verbose_name='Tire'),
        ),
    ]
