# Generated by Django 2.2.3 on 2019-08-05 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='tires',
            field=models.ManyToManyField(blank=True, through='stock.Balance', to='tires.Tire'),
        ),
    ]
