# Generated by Django 2.2.3 on 2019-08-05 15:39

import apps.tires.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(choices=[(175, '175'), (185, '185'), (205, '205')], verbose_name='Width')),
                ('height', models.IntegerField(choices=[(60, '60'), (70, '70'), (80, '80')], verbose_name='Height')),
                ('diameter', models.IntegerField(choices=[(13, '13'), (14, '14'), (15, '15')], verbose_name='Diameter')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'unique_together': {('width', 'height', 'diameter')},
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('season', apps.tires.fields.SeasonField(choices=[('winter', 'Winter'), ('summer', 'Summer'), ('all', 'All seasons')], default='all', help_text='Optimal season for a tire using.', max_length=32, verbose_name='Season')),
                ('count', models.PositiveIntegerField(default=0, help_text='How many tires are stored in a stock', verbose_name='Count in stock')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.Manufacturer', verbose_name='Manufacturer')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.Size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Tire',
                'verbose_name_plural': 'Tires',
                'unique_together': {('manufacturer', 'size', 'title')},
            },
        ),
    ]
