# Generated by Django 2.2.3 on 2019-08-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='count',
        ),
    ]
